repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: tflint

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v2.1.0
    hooks:
      - id: tofu_fmt
      - id: tofu_validate

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        args: ['--project-dir', 'ansible/', "--config-file", './ansible/.ansible-lint.yml']
        additional_dependencies:
          - ansible

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        entry: black
        args: [--config=python-tools/pyproject.toml, --diff, python-tools/]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff
        entry: ruff
        args: [--config=python-tools/pyproject.toml]
