---
universal_auth_client_id: "5fd72230-4272-4738-851f-17c1f83b0e31"
universal_auth_client_secret: "{{ lookup('ansible.builtin.env', 'TF_VAR_infisical_client_secret') }}"
project_id: "c6b11c29-4e36-472e-93be-54130b65a987"
path: "/"
env_slug: "prod"

CIVICRM_PW:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='CIVICRM_PW', env_slug=env_slug) }}"

N8N_ADMIN_PW:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='N8N_ADMIN_PW', env_slug=env_slug) }}"

KESTRA_ADMIN_PW:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='KESTRA_ADMIN_PW', env_slug=env_slug) }}"

CIVICRM_API_KEY:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='SECRET_CIVICRM_API_KEY', env_slug=env_slug) }}"

CIVICRM_NEON_WAREHOUSE_HOST:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='CIVICRM_NEON_WAREHOUSE_HOST', env_slug=env_slug) }}"

CIVICRM_NEON_WAREHOUSE_PW:
  "{{ lookup('infisical.vault.read_secrets', universal_auth_client_id=universal_auth_client_id,
  universal_auth_client_secret=universal_auth_client_secret,
  project_id=project_id, path=path, secret_name='CIVICRM_NEON_WAREHOUSE_PW', env_slug=env_slug) }}"


n8n_admin_email: info@correlaid.org
kestra_admin_email: info@correlaid.org
