[book]
authors = ["jstet"]
language = "en"
src = "src"
title = "CiviCRM Daten analysieren und visualisieren"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding